export const ListData =[
    {
        id:1,
        title: "A Great Apartmetn Next to the Beach",
        img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
        bedRoom:2,
        bathroom:1,
        price:1000,
        address:"456 park Avenu,London",
        latitude: 51.5074,
        longitude: -0.1278,
    },
    {
        id:2,
        title: "A Great Apartmetn Next to the Beach",
        img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
        bedRoom:2,
        bathroom:1,
        price:1000,
        address:"456 park Avenu,London",
        latitude: 51.5070,
        longitude: -0.1275,
    },
    // {
    //     id:3,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:4,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:5,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:6,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:7,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:8,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:9,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:10,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
    // {
    //     id:11,
    //     title: "A Great Apartmetn Next to the Beach",
    //     img:"https://a31eb4a396f4ecf27fae.b-cdn.net/wp-content/uploads/2021/04/Link-detatched-house.jpg",
    //     bedRoom:2,
    //     bathroom:1,
    //     price:1000,
    //     address:"456 park Avenu,London",
    //     latitude: 51.5074,
    //     longitude: -0.1278,
    // },
]